version: "3"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    environment:
      # - NODE_ENV=production
      - BACKEND_HOST=localhost
      - BACKEND_PORT=8000
    tty: true
    volumes:
      - ./:/home/node/app:z
    ports:
      - "8081:3000"
    command: "./entrypoint.sh"
    # command: "tail -f /dev/null"